AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  roleName:
    Type: String
    Default: 'OrganizationFormationBuildAccessRole'

  assumeRolePrincipals:
    Type: CommaDelimitedList
    Default: ''

Conditions:

  hasPrincipal: !Not [ !Equals [ '', !Join [ '', !Ref assumeRolePrincipals ] ] ]

Resources:
  OrganizationFormationBuildAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref roleName
      Description: 'IAM Role used for cross account access by OrgFormation build process'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess # see: https://github.com/org-formation/org-formation-cli/blob/master/docs/least-priviledge.md
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: !If [ hasPrincipal, !Ref assumeRolePrincipals, !Sub 'arn:aws:iam::${AWS::AccountId}:root' ]

Outputs:
  RoleArn:
    Value: !GetAtt OrganizationFormationBuildAccessRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-arn
