AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  minimumPasswordLength:
    Type: Number
    Default: 14
    MinValue: 6
    MaxValue: 128

Resources:

  PasswordPolicyIAM:
    Type: Community::IAM::PasswordPolicy
    Properties:
      MaxPasswordAge: 90
      MinimumPasswordLength: !Ref minimumPasswordLength
      RequireLowercaseCharacters: true
      RequireNumbers: true
      RequireSymbols: true
      RequireUppercaseCharacters: true
      PasswordReusePrevention: 24
      AllowUsersToChangePassword: true
