AWSTemplateFormatVersion: '2010-09-09-OC'

Parameters:

  targetIds:
    Type: CommaDelimitedList

Resources:

  S3AccountPublicAccessBlock:
    Type: Community::S3::PublicAccessBlock
    OrganizationBinding: !Ref PrimaryRegionBinding
    Properties:
      BlockPublicAcls: true
      BlockPublicPolicy: true
      IgnorePublicAcls: true
      RestrictPublicBuckets: true

  EbsEncryptionDefaults:
    Type: Community::Organizations::EbsEncryptionDefaults
    OrganizationBinding: !Ref AllRegionsBinding
    Properties:
      EnableEbsEncryptionByDefault: true

  AiOptOutPolicy:
    Type: Community::Organizations::Policy
    OrganizationBinding: !Ref OrganizationsPolicyBinding
    Properties:
      Content: !ReadFile ./resources/ai-trainig-optout-policy.json
      Description: Opts out of sharing data for AI training purposes
      Name: GlobalAiOptOut
      PolicyType: AISERVICES_OPT_OUT_POLICY
      TargetIds: !Ref targetIds
