AWSTemplateFormatVersion: '2010-09-09-OC'

Resources:

  S3AccountPublicAccessBlock:
    Type: "Community::S3::PublicAccessBlock"
    OrganizationBinding: !Ref AllAccountsPrimaryRegionBinding
    Properties:
      BlockPublicAcls: true
      BlockPublicPolicy: true
      IgnorePublicAcls: true
      RestrictPublicBuckets: true

  EbsEncryptionDefaults:
    Type: "Community::Organizations::EbsEncryptionDefaults"
    OrganizationBinding: !Ref AllAccountsAllRegionsBinding
    Properties:
      EnableEbsEncryptionByDefault: true

  AiOptOutPolicy:
    Type: Community::Organizations::Policy
    OrganizationBinding: !Ref ManagementAccountPrimaryRegionBinding
    Properties:
      Content: !ReadFile ./resources/ai-trainig-optout-policy.json
      Description: Opts out of sharing data for AI training purposes
      Name: AiTrainingOptOut
      PolicyType: AISERVICES_OPT_OUT_POLICY
      TargetIds: !Ref organizationPrincipalId