AWSTemplateFormatVersion: '2010-09-09-OC'

OrganizationBindings:
 ScpTargetBinding: # empty default

Conditions:
  createPolicy: !Not [!Equals [Fn::TargetCount ScpTargetBinding, 0]]


Parameters:
  targetIds:
    Type: CommaDelimitedList

Resources:
  OrganizationPolicy:
    Condition: createPolicy
    Type: Community::Organizations::Policy
    Properties:
      Description: Deny everything, used for quarantine or suspended ou
      Name: DenyEverything
      PolicyType: SERVICE_CONTROL_POLICY
      TargetIds: Fn::EnumTargetAccounts ScpTargetBinding ${account}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyEverything
            Effect: Deny
            Action: "*"
            Resource: "*"