AWSTemplateFormatVersion: '2010-09-09-OC'

OrganizationBindings:
 ScpTargetBinding: # empty default

Conditions:
  createPolicy: !Not [!Equals [Fn::TargetCount ScpTargetBinding, 0]]

Parameters:
  targetIds:
    Type: CommaDelimitedList

Resources:
  OrganizationPolicy:
    Condition: createPolicy
    Type: Community::Organizations::Policy
    Properties:
      Description: Deny running EC2 instances larger than 4xlarge
      Name: DenyLargeEC2Instances
      PolicyType: SERVICE_CONTROL_POLICY
      TargetIds: Fn::EnumTargetAccounts ScpTargetBinding ${account}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyLargerThan4XLarge
            Effect: Deny
            Action:
              - "ec2:RunInstances"
              - "ec2:ModifyInstanceAttribute"
            Resource: "arn:aws:ec2:*:*:instance/*"
            Condition:
              ForAnyValue:StringNotLike:
                "ec2:InstanceType":
                  - "*.nano"
                  - "*.small"
                  - "*.micro"
                  - "*.medium"
                  - "*.large"
                  - "*.xlarge"
                  - "*.2xlarge"
                  - "*.4xlarge"