AWSTemplateFormatVersion: '2010-09-09-OC'
Description: Default organization blueprint

Organization:

  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      Alias: management-{{organization-name}}
      RootEmail: aws+management@{{email-domain}}
      AccountName: Management Account
      AccountId: '{{management-account-id}}'
      Tags:
        budget-alarm-threshold: 200
        account-owner-email: me@{{email-domain}}

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:

  ProductionOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: production
      Accounts:

  DevelopmentTeamOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development-teams
      Accounts:

  SharedOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: shared
      Accounts:
        - !Ref ComplianceAccount
        - !Ref OrgBuildAccount

  ComplianceAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: compliance-{{organization-name}}
      AccountName: Compliance Account
      RootEmail: aws+compliance@{{email-domain}}
      Tags:
        budget-alarm-threshold: 200
        account-owner-email: compliance@{{email-domain}}

  OrgBuildAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: org-build-{{organization-name}}
      AccountName: Organization Build Account
      RootEmail: aws+org-build@{{email-domain}}
      Tags:
        budget-alarm-threshold: 200
        account-owner-email: me@{{email-domain}}
