AWSTemplateFormatVersion: '2010-09-09-OC'
Description: Default organization blueprint

Organization:

  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      Alias: management-{{organization-name}}
      RootEmail: aws+management@{{email-domain}}
      AccountName: Management Account
      AccountId: '{{management-account-id}}'
      Tags:
        budget-alarm-threshold: 200
        account-owner-email: me@{{email-domain}}

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:

  ProductionOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: production
      Accounts:

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development
      Accounts:

  SharedOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: shared
      Accounts:
        - !Ref SecurityAccount
        - !Ref LogArchiveAccount
        - !Ref OrgBuildAccount

  SecurityAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: security-{{organization-name}}
      AccountName: Security Account
      RootEmail: aws+security@{{email-domain}}
      Tags:
        budget-alarm-threshold: 200
        account-owner-email: security@{{email-domain}}

  LogArchiveAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: log-archive-{{organization-name}}
      AccountName: Log Archive Account
      RootEmail: aws+log-archive@{{email-domain}}
      Tags:
        budget-alarm-threshold: 200
        account-owner-email: log-archive@{{email-domain}}

  OrgBuildAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: org-build-{{organization-name}}
      AccountName: Organization Build Account
      RootEmail: aws+org-build@{{email-domain}}
      Tags:
        budget-alarm-threshold: 200
        account-owner-email: me@{{email-domain}}
